openapi: 3.0.1
info:
  title: Science Fair System
  description: Documentation of the Science Fair Endpoints
  version: 0.0.1

tags:
  - name: teacher
    description: Teachers endpoints

paths:
  /teacher:
    post:
      tags:
        - teacher
      summary: Create a new teacher
      operationId: createTeacher
      requestBody:
        description: Teacher info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'

  /teacher/{teacherRegistration}:
    get:
      tags:
        - teacher
      summary: Get a Teacher
      operationId: getTeacher
      parameters:
        - name: teacherRegistration
          in: path
          description: Teacher registration
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Teacher not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'
    delete:
      tags:
        - teacher
      summary: Delete a Teacher
      operationId: deleteTeacher
      parameters:
        - name: teacherRegistration
          in: path
          description: Teacher registration
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Teacher not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'
    patch:
      tags:
        - teacher
      summary: Update a Teacher
      operationId: updateTeacher
      parameters:
        - name: teacherRegistration
          in: path
          description: Teacher registration
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Teacher info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Student not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - name
        - registration
        - email
      properties:
        name:
          type: string
          example: Ricardo Randolfo dos Santos
        registration:
          type: integer
          format: int64
          example: 123456
        email:
          type: string
          example: ricardo@email.com

    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
          example: Ricardo Randolfo dos Santos
        email:
          type: string
          example: ricardo@email.com

    UserResponse:
      type: object
      properties:
        registration:
          type: integer
          format: int64
          example: 123456
        name:
          type: string
          example: Ricardo Randolfo dos Santos
        email:
          type: string
          example: ricardo@email.com
        active:
          type: boolean
          example: true
        userType:
          type: string
          example: TEACHER

    BadRequestResponse:
      type: object
      properties:
        propertyName:
          type: string
          description: Error message
          example: can't be empty

    ResourceNotFoundResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: Error timestamp
          example: 17-Feb-2023 04:07:04
        message:
          type: string
          description: Error message
          example: User not found