openapi: 3.0.1
info:
  title: Science Fair System
  description: Documentation of the Science Fair Endpoints
  version: 0.0.1

tags:
  - name: topic
    description: Assessment's topic endpoints

paths:
  /class:
    post:
      tags:
        - topic
      summary: Create topics
      operationId: createTopics
      requestBody:
        description: Topics info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTopicsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'

components:
  schemas:
    CreateTopicsRequest:
      type: array
      items:
        $ref: '#/components/schemas/TopicRequest'

    TopicRequest:
      type: object
      required:
        - name
        - areaOfKnowledge
      properties:
        name:
          type: string
          example: Biology
        areaOfKnowledge:
          type: object
          $ref: '#/components/schemas/AreaOfKnowledgeRequest'

    AreaOfKnowledgeRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Natural Science

    BadRequestResponse:
      type: object
      properties:
        propertyName:
          type: string
          description: Error message
          example: can't be empty

    ResourceNotFoundResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: Error timestamp
          example: 17-Feb-2023 04:07:04
        message:
          type: string
          description: Error message
          example: Topic not found