openapi: 3.0.1
info:
  title: Science Fair System
  description: Documentation of the Science Fair Endpoints
  version: 0.0.1

tags:
  - name: areaOfKnowledge
    description: Area of Knowledge's topic endpoints

paths:
  /area-of-knowledge:
    post:
      tags:
        - areaOfKnowledge
      summary: Create Area of Knowledge
      operationId: createAreaOfKnowledge
      requestBody:
        description: Area of Knowledge info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAreaOfKnowledgeRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaOfKnowledgeResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'

  /area-of-knowledge/{id}:
    get:
      tags:
        - areaOfKnowledge
      summary: Get Area of Knowledge Details
      operationId: getAreaOfKnowledge
      parameters:
        - name: id
          in: path
          description: Area of Knowledge Id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaOfKnowledgeResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'
    patch:
      tags:
        - areaOfKnowledge
      summary: Update an Area of Knowledge with a list of Topics
      operationId: updateAreaOfKnowledge
      parameters:
        - name: id
          in: path
          description: Area of Knowledge Id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Area of Knowledge info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAreaOfKnowledgeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaOfKnowledgeResponse'
        '404':
          description: Area of Knowledge not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'

    delete:
      tags:
        - areaOfKnowledge
      summary: Delete an Area of Knowledge
      operationId: deleteAreaOfKnowledge
      parameters:
        - name: id
          in: path
          description: Area of Knowledge id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaOfKnowledgeResponse'
        '404':
          description: Area of Knowledge not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundResponse'

  /area-of-knowledge/all:
    get:
      tags:
        - areaOfKnowledge
      summary: Get a list of Areas Of Knowledge
      operationId: getAllAreasOfKnowledge
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AreaOfKnowledgeResponse'

  /area-of-knowledge/all/active:
    get:
      tags:
        - areaOfKnowledge
      summary: Get a list of Active Areas of Knowledge
      operationId: getAllActiveAreasOfKnowledge
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AreaOfKnowledgeResponse'

  /area-of-knowledge/topics/all:
    get:
      tags:
        - areaOfKnowledge
      summary: Get a list of all Topics
      operationId: getAllAreaOfKnowledgeTopics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopicResponse'

components:
  schemas:
    CreateAreaOfKnowledgeRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Natural Science
        topics:
          type: array
          items:
            $ref: '#/components/schemas/TopicRequest'

    UpdateAreaOfKnowledgeRequest:
      type: object
      properties:
        name:
          type: string
          example: Natural Science
        topics:
          type: array
          items:
            $ref: '#/components/schemas/TopicRequest'

    TopicRequest:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Biology

    AreaOfKnowledgeResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Natural Science
        active:
          type: boolean
          example: true
        topics:
          type: array
          items:
            $ref: '#/components/schemas/TopicResponse'

    TopicResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Biology

    BadRequestResponse:
      type: object
      properties:
        propertyName:
          type: string
          description: Error message
          example: can't be empty

    ResourceNotFoundResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: Error timestamp
          example: 17-Feb-2023 04:07:04
        message:
          type: string
          description: Error message
          example: Area of Knowledge not found