openapi: 3.0.1
info:
  title: Science Fair System
  description: Documentation of the Science Fair Endpoints
  version: 0.0.1

tags:
  - name: class
    description: Class endpoints

paths:
  /class:
    post:
      tags:
        - class
      summary: Create a new class
      operationId: createClass
      requestBody:
        description: Class info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClassRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'

  /class/{classId}:
    get:
      tags:
        - class
      summary: Get a Class
      operationId: getClass
      parameters:
        - name: classId
          in: path
          description: Class id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassResponse'
        '404':
          description: Class not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassNotFoundResponse'
    delete:
      tags:
        - class
      summary: Delete a Class
      operationId: deleteClass
      parameters:
        - name: classId
          in: path
          description: Class id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassResponse'
        '404':
          description: Class not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassNotFoundResponse'
    patch:
      tags:
        - class
      summary: Update a Class
      operationId: updateClass
      parameters:
        - name: classId
          in: path
          description: Class id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Class info to save
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClassRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassResponse'
        '404':
          description: Class not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassNotFoundResponse'

  /class/classes/active:
    get:
      tags:
        - class
      summary: Get a list of active classes
      operationId: getAllActiveClasses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClassResponse'


components:
  schemas:
    CreateClassRequest:
      type: object
      required:
        - name
        - gradeYear
      properties:
        name:
          type: string
          maxLength: 10
          example: 211
        gradeYear:
          type: string
          example: EM_2ANO
          enum:
            - EF_5ANO
            - EF_6ANO
            - EF_7ANO
            - EF_8ANO
            - EF_9ANO
            - EM_1ANO
            - EM_2ANO
            - EM_3ANO

    UpdateClassRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 10
          example: 211
        gradeYear:
          type: string
          example: EM_2ANO
          enum:
            - EF_5ANO
            - EF_6ANO
            - EF_7ANO
            - EF_8ANO
            - EF_9ANO
            - EM_1ANO
            - EM_2ANO
            - EM_3ANO

    ClassResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: 211
        gradeYear:
          type: string
          example: EM_2ANO
        active:
          type: boolean
          example: true

    BadRequestResponse:
      type: object
      properties:
        propertyName:
          type: string
          description: Error message
          example: can't be empty

    ClassNotFoundResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: Error timestamp
          example: 17-Feb-2023 04:07:04
        message:
          type: string
          description: Error message
          example: Class not found